<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-02 at 19:07:55.
 */
class PostTest extends PHPUnit_Framework_TestCase {

    protected $request;
    protected $ssl;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->request = new Post(array(
            "q" => "php"
        ), $this->ssl);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Post::sendRequest
     */
    public function testSendRequest() {
        $this->ssl = false;
        $this->setUp();
        $this->assertNotEmpty($this->request->sendRequest("www.google.com/search"));
    }
    
    /**
     * @covers Post::sendRequest
     */
    public function testSendRequestSSL() {
        $this->ssl = true;
        $this->setUp();
        $this->assertNotEmpty($this->request->sendRequest("www.google.com/search"));
    }

}
