<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-02 at 19:06:44.
 */
class DecryptTest extends PHPUnit_Framework_TestCase {

    protected $cipher;
    protected $decrypt;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->cipher = new Encrypt("Some text to decrypt");
        $this->decrypt = new Decrypt($this->cipher->getBinary(), $this->cipher->getKey(), $this->cipher->getIv());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Decrypt::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
